/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : 福田
Source Server Version : 110200
Source Host           : 221.224.132.210:1521
Source Schema         : QEWEBREPOSITORIES

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-08-12 13:05:35
*/


-- ----------------------------
-- Table structure for QEWEB_ASSESS_TEMPLATE
-- ----------------------------
DROP TABLE "QEWEB_ASSESS_TEMPLATE";
CREATE TABLE "QEWEB_ASSESS_TEMPLATE" (
"ID" NUMBER(9) NULL ,
"NAME" NVARCHAR2(255) NULL ,
"WEIGHT" NUMBER(1) NULL ,
"CYCLE_ID" NUMBER(9) NULL ,
"DESCRIBE" NVARCHAR2(255) NULL ,
"ABOLISHED" NUMBER(1) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"CREATE_USER_ID" NUMBER(9) NULL ,
"LAST_UPDATE_TIME" TIMESTAMP(6)  NULL ,
"UPDATE_USER_ID" NUMBER(9) NULL ,
"CREATE_USER_NAME" NVARCHAR2(100) NULL ,
"UPDATE_USER_NAME" NVARCHAR2(100) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "QEWEB_ASSESS_TEMPLATE" IS 'qeweb_assess_template';
COMMENT ON COLUMN "QEWEB_ASSESS_TEMPLATE"."ID" IS '主键';
COMMENT ON COLUMN "QEWEB_ASSESS_TEMPLATE"."WEIGHT" IS '父ID';
COMMENT ON COLUMN "QEWEB_ASSESS_TEMPLATE"."CYCLE_ID" IS '顶级父ID';
COMMENT ON COLUMN "QEWEB_ASSESS_TEMPLATE"."DESCRIBE" IS '模版说明';
COMMENT ON COLUMN "QEWEB_ASSESS_TEMPLATE"."ABOLISHED" IS '废除标记';
COMMENT ON COLUMN "QEWEB_ASSESS_TEMPLATE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "QEWEB_ASSESS_TEMPLATE"."CREATE_USER_ID" IS '创建用户FK';
COMMENT ON COLUMN "QEWEB_ASSESS_TEMPLATE"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "QEWEB_ASSESS_TEMPLATE"."UPDATE_USER_ID" IS '最后更新用户FK';
COMMENT ON COLUMN "QEWEB_ASSESS_TEMPLATE"."CREATE_USER_NAME" IS '创建用户姓名';
COMMENT ON COLUMN "QEWEB_ASSESS_TEMPLATE"."UPDATE_USER_NAME" IS '更新用户姓名';
