/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : 福田
Source Server Version : 110200
Source Host           : 221.224.132.210:1521
Source Schema         : QEWEBREPOSITORIES

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-09-02 10:01:50
*/


-- ----------------------------
-- Table structure for QEWEB_ASSESS_DATAIN
-- ----------------------------
DROP TABLE "QEWEB_ASSESS_DATAIN";
CREATE TABLE "QEWEB_ASSESS_DATAIN" (
"ID" NUMBER(9) NOT NULL ,
"VENDOR_CODE" NVARCHAR2(100) NULL ,
"VENDOR_NAME" NVARCHAR2(100) NULL ,
"MATERIAL_CODE" NVARCHAR2(100) NULL ,
"MATERIAL_NAME" NVARCHAR2(100) NULL ,
"ABOLISHED" NUMBER(1) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"CREATE_USER_ID" NUMBER(9) NULL ,
"LAST_UPDATE_TIME" TIMESTAMP(6)  NULL ,
"UPDATE_USER_ID" NUMBER(9) NULL ,
"CREATE_USER_NAME" NVARCHAR2(100) NULL ,
"UPDATE_USER_NAME" NVARCHAR2(100) NULL ,
"ELEMENT" NVARCHAR2(255) NULL ,
"ELEMENT_VALUE" NVARCHAR2(255) NULL ,
"INDEX_NAME" NVARCHAR2(255) NULL ,
"BRAND_NAME" NVARCHAR2(255) NULL ,
"ASSESS_DATE" TIMESTAMP(6)  NULL ,
"CYCLE_ID" NUMBER(9) NULL ,
"DEFAULT_PURCHASE" NUMBER(11) NULL ,
"FACTORY_NAME" NVARCHAR2(255) NULL ,
"BELONG_DATE" TIMESTAMP(6)  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "QEWEB_ASSESS_DATAIN"."ABOLISHED" IS '废除标记';
COMMENT ON COLUMN "QEWEB_ASSESS_DATAIN"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "QEWEB_ASSESS_DATAIN"."CREATE_USER_ID" IS '创建用户FK';
COMMENT ON COLUMN "QEWEB_ASSESS_DATAIN"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "QEWEB_ASSESS_DATAIN"."UPDATE_USER_ID" IS '最后更新用户FK';
COMMENT ON COLUMN "QEWEB_ASSESS_DATAIN"."CREATE_USER_NAME" IS '创建用户姓名';
COMMENT ON COLUMN "QEWEB_ASSESS_DATAIN"."UPDATE_USER_NAME" IS '更新用户姓名';

-- ----------------------------
-- Table structure for QEWEB_ASSESS_DATAINDETAILS
-- ----------------------------
DROP TABLE "QEWEB_ASSESS_DATAINDETAILS";
CREATE TABLE "QEWEB_ASSESS_DATAINDETAILS" (
"ID" NUMBER(9) NOT NULL ,
"CYCLE_ID" NUMBER(9) NULL ,
"ASSESS_DATE" TIMESTAMP(6)  NULL ,
"BELONG_DATE" TIMESTAMP(6)  NULL ,
"VENDOR_CODE" NVARCHAR2(255) NULL ,
"VENDOR_NAME" NVARCHAR2(255) NULL ,
"BRAND_NAME" NVARCHAR2(255) NULL ,
"FACTORY_NAME" NVARCHAR2(255) NULL ,
"MATERIAL_CODE" NVARCHAR2(100) NULL ,
"MATERIAL_NAME" NVARCHAR2(100) NULL ,
"INDEX_NAME" NVARCHAR2(255) NULL ,
"DIMENSIONS_NAME" NVARCHAR2(255) NULL ,
"MUST_IMPORT_ELEMENTS" NVARCHAR2(255) NULL ,
"NO_IMPORT_ELEMENTS" NVARCHAR2(255) NULL ,
"NO_IMPORT_ELEMENTS_NAME" NVARCHAR2(255) NULL ,
"CYCLE_NAME" NVARCHAR2(255) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Indexes structure for table QEWEB_ASSESS_DATAIN
-- ----------------------------

-- ----------------------------
-- Checks structure for table QEWEB_ASSESS_DATAIN
-- ----------------------------
ALTER TABLE "QEWEB_ASSESS_DATAIN" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QEWEB_ASSESS_DATAIN
-- ----------------------------
ALTER TABLE "QEWEB_ASSESS_DATAIN" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table QEWEB_ASSESS_DATAINDETAILS
-- ----------------------------

-- ----------------------------
-- Checks structure for table QEWEB_ASSESS_DATAINDETAILS
-- ----------------------------
ALTER TABLE "QEWEB_ASSESS_DATAINDETAILS" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QEWEB_ASSESS_DATAINDETAILS
-- ----------------------------
ALTER TABLE "QEWEB_ASSESS_DATAINDETAILS" ADD PRIMARY KEY ("ID");
