/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : 福田
Source Server Version : 110200
Source Host           : 221.224.132.210:1521
Source Schema         : QEWEBREPOSITORIES

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-08-12 16:31:22
*/


-- ----------------------------
-- Table structure for QEWEB_ASSESS_DIMENSIONS
-- ----------------------------
DROP TABLE "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS";
CREATE TABLE "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS" (
"ID" NUMBER(9) NOT NULL ,
"CODE" NVARCHAR2(50) NULL ,
"DIM_NAME" NVARCHAR2(255) NULL ,
"REMARKS" NVARCHAR2(255) NULL ,
"ABOLISHED" NUMBER(1) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"CREATE_USER_ID" NUMBER(9) NULL ,
"LAST_UPDATE_TIME" TIMESTAMP(6)  NULL ,
"UPDATE_USER_ID" NUMBER(9) NULL ,
"CREATE_USER_NAME" NVARCHAR2(100) NULL ,
"UPDATE_USER_NAME" NVARCHAR2(100) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS"."ABOLISHED" IS '废除标记';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS"."CREATE_USER_ID" IS '创建用户FK';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS"."UPDATE_USER_ID" IS '最后更新用户FK';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS"."CREATE_USER_NAME" IS '创建用户姓名';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS"."UPDATE_USER_NAME" IS '更新用户姓名';

-- ----------------------------
-- Indexes structure for table QEWEB_ASSESS_DIMENSIONS
-- ----------------------------

-- ----------------------------
-- Checks structure for table QEWEB_ASSESS_DIMENSIONS
-- ----------------------------
ALTER TABLE "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QEWEB_ASSESS_DIMENSIONS
-- ----------------------------
ALTER TABLE "QEWEBREPOSITORIES"."QEWEB_ASSESS_DIMENSIONS" ADD PRIMARY KEY ("ID");
