/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : 福田
Source Server Version : 110200
Source Host           : 221.224.132.210:1521
Source Schema         : QEWEBREPOSITORIES

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-08-12 15:44:01
*/


-- ----------------------------
-- Table structure for QEWEB_ASSESS_INDEX
-- ----------------------------
DROP TABLE "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX";
CREATE TABLE "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX" (
"ID" NUMBER(9) NULL ,
"INDEX_NAME" NVARCHAR2(50) NULL ,
"DESCRIBE" NVARCHAR2(255) NULL ,
"OTVD" NUMBER(1) NULL ,
"OTVV" NUMBER(1) NULL ,
"INDEX_TYPE" NUMBER(1) NULL ,
"DIMENSIONS_ID" NUMBER(9) NULL ,
"REMARK" NVARCHAR2(255) NULL ,
"ABOLISHED" NUMBER(1) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"CREATE_USER_ID" NUMBER(9) NULL ,
"LAST_UPDATE_TIME" TIMESTAMP(6)  NULL ,
"UPDATE_USER_ID" NUMBER(9) NULL ,
"CREATE_USER_NAME" NVARCHAR2(100) NULL ,
"UPDATE_USER_NAME" NVARCHAR2(100) NULL ,
"INDEX_ID" NUMBER(9) NULL ,
"HIERARCHY" NUMBER(9) NULL ,
"CODE" NVARCHAR2(50) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX" IS 'qeweb_assess_index';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."ID" IS '主键';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."INDEX_NAME" IS '名称';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."OTVD" IS '一票否决维度';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."OTVV" IS '一票否决供应商';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."REMARK" IS '备注';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."ABOLISHED" IS '废除标记';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."CREATE_USER_ID" IS '创建用户FK';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."UPDATE_USER_ID" IS '最后更新用户FK';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."CREATE_USER_NAME" IS '创建用户姓名';
COMMENT ON COLUMN "QEWEBREPOSITORIES"."QEWEB_ASSESS_INDEX"."UPDATE_USER_NAME" IS '更新用户姓名';
