CREATE TABLE QEWEB_MATERIAL_PLAN
(
  ID                NUMBER(9)   PRIMARY KEY       NOT NULL,
  MATERIAL_ID          NUMBER(9),
  PLAN_NUM          NUMBER(11,2),
  PLAN_TIME         TIMESTAMP(6),
  PUBLISH_STATUS    NUMBER(1),
  PUBLISH_TIME       TIMESTAMP(6),
  PUBLISH_USER_ID   NUMBER(9),
  BUYER_ID           NUMBER(9),
  ABOLISHED         NUMBER(1),
  CREATE_TIME       TIMESTAMP(6),
  CREATE_USER_ID    NUMBER(9),
  LAST_UPDATE_TIME  TIMESTAMP(6),
  UPDATE_USER_ID    NUMBER(9),
  CREATE_USER_NAME  NVARCHAR2(100),
  UPDATE_USER_NAME  NVARCHAR2(100)
);
CREATE TABLE QEWEB_MATERIAL_VENDOR_PLAN
(
  ID                NUMBER(9)   PRIMARY KEY       NOT NULL,
  PLAN_ID       	NUMBER(9),
  VENDOR_ID          NUMBER(9),
  PLAN_NUM          NUMBER(11,2),
  ABOLISHED         NUMBER(1),
  CREATE_TIME       TIMESTAMP(6),
  CREATE_USER_ID    NUMBER(9),
  LAST_UPDATE_TIME  TIMESTAMP(6),
  UPDATE_USER_ID    NUMBER(9),
  CREATE_USER_NAME  NVARCHAR2(100),
  UPDATE_USER_NAME  NVARCHAR2(100)
);




