   ALTER TABLE QEWEB_DELIVERY
 ADD (ANZPK  NUMBER(13,2));


   ALTER TABLE QEWEB_DELIVERY_ITEM
 ADD (YSTS NVARCHAR2(100));
 
    ALTER TABLE QEWEB_DELIVERY_ITEM
 ADD (PLAN_DELIVERY_DATE TIMESTAMP(6));

CREATE TABLE QEWEB_BASE_FILE
(
  ID                    NUMBER(9)               NOT NULL,
  BILL_ID      NUMBER(9)               NOT NULL,
  BILL_TYPE          NVARCHAR2(100),
  FILE_NAME          NVARCHAR2(100),
  FILE_PATH            NVARCHAR2(100),
  FILE_CONTENT          BLOB,
  ABOLISHED             NUMBER(1)               NOT NULL,
  CREATE_TIME           TIMESTAMP(6),
  CREATE_USER_ID        NUMBER(9),
  LAST_UPDATE_TIME      TIMESTAMP(6),
  UPDATE_USER_ID        NUMBER(9),
  CREATE_USER_NAME      NVARCHAR2(100),
  UPDATE_USER_NAME      NVARCHAR2(100)
)