CREATE OR REPLACE VIEW "VIEW_VENDOR" AS 
SELECT
V.ID AS V_ID,
VP.ID AS VP_ID,
VP.NAME AS VP_NAME,
VP.CODE AS VP_CODE,
V.CODE AS V_CODE,
V.NAME AS V_NAME,
V.SHORT_NAME AS V_SHORT_NAME,
V.PROPERTY AS V_PROPERTY,
V.COUNTRY AS V_COUNTRY,
V.PROVINCE AS V_PROVINCE,
V.CITY AS V_CITY,
V.ADDRESS AS V_ADDRESS,
V.MATERIAL_ID AS V_MATERIAL_ID,
V.MATERIAL_TYPE_ID AS V_MATERIAL_TYPE_ID,
V.PRODUCT_LINE AS V_PRODUCT_LINE,
V.MAIN_PRODUCT AS V_MAIN_PRODUCT,
V.ORG_ID AS V_ORG_ID,
V.PHASE_ID AS V_PHASE_ID,
V.COUNTRY_TEXT AS V_COUNTRY_TEXT,
V.PROVINCE_TEXT AS V_PROVINCE_TEXT,
V.VENDOR_TYPE AS V_VENDOR_TYPE,
V.CITY_TEXT AS V_CITY_TEXT,
V.DISTRICT_TEXT AS V_DISTRICT_TEXT,
V.PRODUCT_POWER AS V_PRODUCT_POWER,
V.CURRENT_VERSION AS V_CURRENT_VERSION,
V.VENDOR_LEVEL AS V_VENDOR_LEVEL,
V.VENDOR_CLASSIFY AS V_VENDOR_CLASSIFY,
V.VENDOR_CLASSIFY2 AS V_VENDOR_CLASSIFY2
FROM
QEWEB_VENDOR_BASE_INFO V
INNER JOIN QEWEB_VENDOR_PHASE VP ON V.PHASE_ID = VP.ID;

