DROP TABLE QEWEB_BUYER_VENDOR_REL CASCADE CONSTRAINTS;

CREATE TABLE QEWEB_BUYER_VENDOR_REL
(
  ID                NUMBER(9)                   NOT NULL,
  BUYER_ID       NUMBER(9),
  VENDOR_ID          NUMBER(9),

 
  ABOLISHED         NUMBER(1),
  CREATE_TIME       TIMESTAMP(6),
  CREATE_USER_ID    NUMBER(9),
  LAST_UPDATE_TIME  TIMESTAMP(6),
  UPDATE_USER_ID    NUMBER(9),
  CREATE_USER_NAME  NVARCHAR2(100),
  UPDATE_USER_NAME  NVARCHAR2(100)
);



ALTER TABLE QEWEB_BUYER_VENDOR_REL ADD (
  CONSTRAINT PK_QEWEB_BUYER_VENDOR_REL
  PRIMARY KEY
  (ID));
  
  
  
Insert into QEWEB_VIEW
   (ID, VIEW_CODE, VIEW_NAME, VIEW_URL, VIEW_TYPE, 
    PARENT_ID, IS_LEAF, MENU_SN, ABOLISHED, CREATE_TIME, 
    CREATE_USER_ID, LAST_UPDATE_TIME, UPDATE_USER_ID, CREATE_USER_NAME, UPDATE_USER_NAME)
 Values
   (5986622, 'vendorBuyerRel', '供应商采购组织管理', '/manager/vendor/buyerVendorRel', 0, 
    1180, 0, 15, 0, TO_TIMESTAMP('2016/3/23 10:14:08.692000','YYYY/fmMMfm/fmDDfm fmHH24fm:MI:SS.FF'), 
    1, TO_TIMESTAMP('2016/3/23 10:14:08.692000','YYYY/fmMMfm/fmDDfm fmHH24fm:MI:SS.FF'), 1, '超级管理员,', '超级管理员,');
COMMIT;
