alter table qeweb_receive add store_code nvarchar2(100);

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_1 TO ATTR1;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_2 TO ATTR2;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_3 TO ATTR3;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_4 TO ATTR4;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_5 TO ATTR5;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_6 TO ATTR6;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_7 TO ATTR7;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_8 TO ATTR8;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_9 TO ATTR9;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_10 TO ATTR10;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_11 TO ATTR11;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_12 TO ATTR12;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_13 TO ATTR13;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_14 TO ATTR14;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_15 TO ATTR15;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_16 TO ATTR16;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_17 TO ATTR17;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_18 TO ATTR18;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_19 TO ATTR19;

ALTER TABLE QEWEB_RECEIVE_ITEM RENAME COLUMN ATTR_20 TO ATTR20;


ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_1 TO ATTR1;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_2 TO ATTR2;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_3 TO ATTR3;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_4 TO ATTR4;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_5 TO ATTR5;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_6 TO ATTR6;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_7 TO ATTR7;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_8 TO ATTR8;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_9 TO ATTR9;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_10 TO ATTR10;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_11 TO ATTR11;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_12 TO ATTR12;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_13 TO ATTR13;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_14 TO ATTR14;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_15 TO ATTR15;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_16 TO ATTR16;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_17 TO ATTR17;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_18 TO ATTR18;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_19 TO ATTR19;

ALTER TABLE QEWEB_RECEIVE RENAME COLUMN ATTR_20 TO ATTR20;