create table QEWEB_DELIVERY_PC
(
  ID               NUMBER(11)   PRIMARY KEY not null,
  DELIVERY_ITEM_ID NUMBER(11) not null,
  ASN_CODE  	   NVARCHAR2(50) not null,
  BOX_COUNT        NUMBER(11) not null,
  PRINT_STATUS     NUMBER(1),
  CREATE_USER_ID   NUMBER(11),
  CREATE_USER_NAME NVARCHAR2(255),
  CREATE_TIME      DATE,
  UPDATE_USER_ID   NUMBER(11),
  UPDATE_USER_NAME NVARCHAR2(255),
  LAST_UPDATE_TIME DATE,
  ABOLISHED        NUMBER(1) not null
);

create table QEWEB_DELIVERY_DT
(
  ID               NUMBER(11)   PRIMARY KEY not null,
  DELIVERY_PC_ID   NUMBER(11) not null,
  ASN_CODE  	   NVARCHAR2(50) not null,
  PRINT_STATUS     NUMBER(1),
  CREATE_USER_ID   NUMBER(11),
  CREATE_USER_NAME NVARCHAR2(255),
  CREATE_TIME      DATE,
  UPDATE_USER_ID   NUMBER(11),
  UPDATE_USER_NAME NVARCHAR2(255),
  LAST_UPDATE_TIME DATE,
  ABOLISHED        NUMBER(1) not null
);

