CREATE TABLE QEWEB_WARN_MAIN
(
  ID                NUMBER(9)   PRIMARY KEY       NOT NULL,
  CODE              NVARCHAR2(100),
  MODULE_NAME       NVARCHAR2(100),
  NAME              NVARCHAR2(100),
  CONTENT           NVARCHAR2(255),
  WARN_CONTENT      NVARCHAR2(255),
  WARN_TIME         NUMBER,
  IS_VENDOR         NUMBER(1),
  ENABLE_STATUS     NUMBER(1),
  ABOLISHED         NUMBER(1),
  CREATE_TIME       TIMESTAMP(6),
  CREATE_USER_ID    NUMBER(9),
  LAST_UPDATE_TIME  TIMESTAMP(6),
  UPDATE_USER_ID    NUMBER(9),
  CREATE_USER_NAME  NVARCHAR2(100),
  UPDATE_USER_NAME  NVARCHAR2(100)
);

CREATE TABLE QEWEB_WARN_ITEM
(
  ID                NUMBER(9)   PRIMARY KEY       NOT NULL,
  WARN_MAIN_ID      NUMBER(9),
  WARN_CONTENT      NVARCHAR2(255),
  WARN_TIME         NUMBER,
  ROLE_ID       	NUMBER(9),
  ABOLISHED         NUMBER(1),
  CREATE_TIME       TIMESTAMP(6),
  CREATE_USER_ID    NUMBER(9),
  LAST_UPDATE_TIME  TIMESTAMP(6),
  UPDATE_USER_ID    NUMBER(9),
  CREATE_USER_NAME  NVARCHAR2(100),
  UPDATE_USER_NAME  NVARCHAR2(100)
);

CREATE TABLE QEWEB_WARN_MESSAGE
(
  ID                NUMBER(9)   PRIMARY KEY       NOT NULL,
  WARN_MAIN_ID      NUMBER(9),
  USER_ID       	NUMBER(9),
  BILL_ID       	NUMBER(9),
  BILL_TYPE       	NVARCHAR2(100),
   WARN_TITLE      NVARCHAR2(100),
  WARN_MESSAGE      NVARCHAR2(255),
  IS_READ           NUMBER(1),
  ABOLISHED         NUMBER(1),
  CREATE_TIME       TIMESTAMP(6),
  CREATE_USER_ID    NUMBER(9),
  LAST_UPDATE_TIME  TIMESTAMP(6),
  UPDATE_USER_ID    NUMBER(9),
  CREATE_USER_NAME  NVARCHAR2(100),
  UPDATE_USER_NAME  NVARCHAR2(100)
);