CREATE TABLE QEWEB_HOLIDAYS
(
  ID                NUMBER(11)   PRIMARY KEY       NOT NULL,
  NAME              NVARCHAR2(100),
  YEAR         NUMBER,
  MONTH         NUMBER,
  DAY         NUMBER,
  DAY_TIME     TIMESTAMP(6),
 
  ABOLISHED         NUMBER(1),
  CREATE_TIME       TIMESTAMP(6),
  CREATE_USER_ID    NUMBER(9),
  LAST_UPDATE_TIME  TIMESTAMP(6),
  UPDATE_USER_ID    NUMBER(9),
  CREATE_USER_NAME  NVARCHAR2(100),
  UPDATE_USER_NAME  NVARCHAR2(100)
);
CREATE TABLE QEWEB_CLASS_SYSTEM
(
  ID                NUMBER(11)   PRIMARY KEY       NOT NULL,
  NAME              NVARCHAR2(100),
  BILL_TYPE         NUMBER(1),
  REMARKS           NVARCHAR2(100),  
  MORNING_START        NUMBER(3,1),
  MORNING_END          NUMBER(3,1),
  AFTER_START          NUMBER(3,1),
  AFTER_END          NUMBER(3,1),
  MONTH              NUMBER,
 
  ABOLISHED         NUMBER(1),
  CREATE_TIME       TIMESTAMP(6),
  CREATE_USER_ID    NUMBER(9),
  LAST_UPDATE_TIME  TIMESTAMP(6),
  UPDATE_USER_ID    NUMBER(9),
  CREATE_USER_NAME  NVARCHAR2(100),
  UPDATE_USER_NAME  NVARCHAR2(100)
);
 
 ALTER TABLE QEWEB_USER
 ADD (CLASS_SYSTEM_ID  NUMBER(11));


