ALTER TABLE QEWEB_VENDOR_MATERIAL_REL
 ADD (FACTORY_ID  NUMBER(11));
 
 ALTER TABLE QEWEB_VENDOR_MATERIAL_REL
 ADD (MAX_PACKAGE_QTY  NUMBER(11,2));
 
 ALTER TABLE QEWEB_VENDOR_MATERIAL_REL
 ADD (MIN_PACKAGE_QTY  NUMBER(11,2));