	ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
	 ADD (BALANCE_TIME  TIMESTAMP(6));
	 
	 	ALTER TABLE QEWEB_RECEIVE_ITEM
	 ADD (BALANCE_TIME  TIMESTAMP(6));
	 
	 ALTER TABLE QEWEB_PURCHASE_ORDER
 ADD (UDATE  TIMESTAMP(6));