ALTER TABLE QEWEB_DELIVERY
	 ADD (YSTS NUMBER);

COMMENT ON COLUMN "QEWEB_DELIVERY"."YSTS" IS '物流天数';

ALTER TABLE QEWEB_DELIVERY
	 ADD (PLAN_DELIVERY_DATE TIMESTAMP(6));

COMMENT ON COLUMN "QEWEB_DELIVERY"."PLAN_DELIVERY_DATE" IS '预计到货时间';



ALTER TABLE QEWEB_DELIVERY_ITEM   DROP COLUMN  YSTS;
ALTER TABLE QEWEB_DELIVERY_ITEM   DROP COLUMN  PLAN_DELIVERY_DATE;