ALTER TABLE "QEWEB_FEEDBACK"
ADD ( "ROLE_TYPE" NVARCHAR2(11) NULL  ) ;

COMMENT ON COLUMN "QEWEB_FEEDBACK"."ROLE_TYPE" IS '创建人角色类型';


ALTER TABLE "QEWEB_PURCHASE_ORDER"
ADD ( "IS_REJECT" NUMBER(1) DEFAULT 0  NULL  ) ;

COMMENT ON COLUMN "QEWEB_PURCHASE_ORDER"."IS_REJECT" IS '是否存在驳回记录';