ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
	 ADD (ZSFXP NVARCHAR2(50));

COMMENT ON COLUMN "QEWEB_PURCHASE_ORDER_ITEM"."ZSFXP" IS '是否新品，X为新品，空为量产';

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
	 ADD (ZWQSL NVARCHAR2(50));

COMMENT ON COLUMN "QEWEB_PURCHASE_ORDER_ITEM"."ZWQSL" IS 'SAP未清数量';


ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
	 ADD (ZSLSX NVARCHAR2(50));

COMMENT ON COLUMN "QEWEB_PURCHASE_ORDER_ITEM"."ZSLSX" IS '订单数量上限';


------------------------改精度
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (ORDER_QTY2 number(11,3));

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (SUR_ORDER_QTY2 number(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set ORDER_QTY2=ORDER_QTY,SUR_ORDER_QTY2=SUR_ORDER_QTY;

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM DROP COLUMN ORDER_QTY;    
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM DROP COLUMN SUR_ORDER_QTY;  

alter table QEWEB_PURCHASE_ORDER_ITEM rename column ORDER_QTY2 to ORDER_QTY;
alter table QEWEB_PURCHASE_ORDER_ITEM rename column SUR_ORDER_QTY2 to SUR_ORDER_QTY;

COMMENT ON COLUMN "QEWEB_PURCHASE_ORDER_ITEM"."ORDER_QTY" IS '订单数量';
COMMENT ON COLUMN "QEWEB_PURCHASE_ORDER_ITEM"."SUR_ORDER_QTY" IS '订单剩余匹配数量';




