--¸Ä¾«¶È
ALTER TABLE QEWEB_DELIVERY_ITEM  
 ADD (DELIVERY_QTY2 number(11,3));

ALTER TABLE QEWEB_DELIVERY_ITEM  
 ADD (RECEIVE_QTY2 number(11,3));

ALTER TABLE QEWEB_DELIVERY_ITEM  
 ADD (UNQUALIFIED_QTY2 number(11,3));

update QEWEB_DELIVERY_ITEM  set DELIVERY_QTY2 =DELIVERY_QTY,RECEIVE_QTY2=RECEIVE_QTY,UNQUALIFIED_QTY2=UNQUALIFIED_QTY;

ALTER TABLE QEWEB_DELIVERY_ITEM  DROP COLUMN DELIVERY_QTY;    
ALTER TABLE QEWEB_DELIVERY_ITEM  DROP COLUMN RECEIVE_QTY;  
ALTER TABLE QEWEB_DELIVERY_ITEM  DROP COLUMN UNQUALIFIED_QTY; 

alter table QEWEB_DELIVERY_ITEM  rename column DELIVERY_QTY2 to DELIVERY_QTY;
alter table QEWEB_DELIVERY_ITEM  rename column RECEIVE_QTY2 to RECEIVE_QTY;
alter table QEWEB_DELIVERY_ITEM  rename column UNQUALIFIED_QTY2 to UNQUALIFIED_QTY;  
  
  
ALTER TABLE QEWEB_RECEIVE_ITEM
 ADD (RECEIVE_QTY2 number(11,3));

ALTER TABLE QEWEB_RECEIVE_ITEM
 ADD (ZDJSL2 number(11,3));

ALTER TABLE QEWEB_RECEIVE_ITEM
 ADD (ZZJBL2 number(11,3));

ALTER TABLE QEWEB_RECEIVE_ITEM
 ADD (ZSJHG2 number(11,3));

ALTER TABLE QEWEB_RECEIVE_ITEM
 ADD (ZLLBL2 number(11,3));

   
update QEWEB_RECEIVE_ITEM set RECEIVE_QTY2=RECEIVE_QTY, ZDJSL2 =ZDJSL,ZZJBL2=ZZJBL,ZSJHG2=ZSJHG,ZLLBL2=ZLLBL;   

ALTER TABLE QEWEB_RECEIVE_ITEM DROP COLUMN RECEIVE_QTY;    
ALTER TABLE QEWEB_RECEIVE_ITEM DROP COLUMN ZDJSL;  
ALTER TABLE QEWEB_RECEIVE_ITEM DROP COLUMN ZZJBL; 
ALTER TABLE QEWEB_RECEIVE_ITEM DROP COLUMN ZSJHG; 
ALTER TABLE QEWEB_RECEIVE_ITEM DROP COLUMN ZLLBL;
   
alter table QEWEB_RECEIVE_ITEM rename column RECEIVE_QTY2 to RECEIVE_QTY;
alter table QEWEB_RECEIVE_ITEM rename column ZDJSL2 to ZDJSL;
alter table QEWEB_RECEIVE_ITEM rename column ZZJBL2 to ZZJBL;  
alter table QEWEB_RECEIVE_ITEM rename column ZSJHG2 to ZSJHG;  
alter table QEWEB_RECEIVE_ITEM rename column ZLLBL2 to ZLLBL; 
   
   