/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : 瑞声
Source Server Version : 110200
Source Host           : 118.178.93.191:1521
Source Schema         : AAC_DEV

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2017-10-13 10:40:35
*/


-- ----------------------------
-- Table structure for QEWEB_VIEW_NO_CHECK_ITEM
-- ----------------------------
DROP TABLE "QEWEB_VIEW_NO_CHECK_ITEM";
CREATE TABLE "QEWEB_VIEW_NO_CHECK_ITEM" (
"ID" NUMBER(10) NOT NULL ,
"ORDER_CODE" VARCHAR2(50 CHAR) NULL ,
"BUYER_CODE" VARCHAR2(50 CHAR) NULL ,
"BUYER_NAME" VARCHAR2(60 CHAR) NULL ,
"VENDOR_CODE" VARCHAR2(50 CHAR) NULL ,
"VENDOR_NAME" VARCHAR2(60 CHAR) NULL ,
"MATERIAL_CODE" VARCHAR2(50 CHAR) NULL ,
"UNIT_NAME" VARCHAR2(50 CHAR) NULL ,
"REC_QTY" NUMBER(13,3) NULL ,
"ITEM_NO" NUMBER(10) NULL ,
"TYPE" CHAR(1 CHAR) NULL ,
"FACTORY_CODE" VARCHAR2(50 CHAR) NULL ,
"FACTORY_NAME" VARCHAR2(50 CHAR) NULL ,
"ORDER_QTY" NUMBER(13,3) NULL ,
"TXZ01" VARCHAR2(20 CHAR) NULL ,
"CREATE_TIME" TIMESTAMP(0)  NULL ,
"BUYER_ID" NUMBER(10) NULL ,
"VENDOR_ID" NUMBER(10) NULL ,
"DATA_TYPE" VARCHAR2(4 CHAR) NULL ,
"GROUP_CODE" VARCHAR2(50 CHAR) NULL ,
"GROUP_NAME" VARCHAR2(50 CHAR) NULL ,
"PRICE" NUMBER(13,3) NULL ,
"INVOICED_QUANTITY" NUMBER(13,3) NULL ,
"CURRENCY_CODE" VARCHAR2(50 CHAR) NULL ,
"DLV_CODE" VARCHAR2(50 CHAR) NULL ,
"MATERIAL_NAME" VARCHAR2(100 CHAR) NULL ,
"MATERIAL_ID" NUMBER(10) NULL ,
"STATE" VARCHAR2(1 CHAR) DEFAULT '0'  NULL ,
"CHANGE_DATE" TIMESTAMP(0)  NULL ,
"ORDER_NO" NUMBER(10) NULL ,
"POST_DATE" TIMESTAMP(0)  NULL ,
"MATERIAL_NO" VARCHAR2(15 CHAR) NULL ,
"MATERIAL_PROJECT" NUMBER(10) NULL ,
"CON_INVOICED_QUANTITY" NUMBER(13,3) NULL ,
"CON_PRICE" NUMBER(13,3) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."ORDER_CODE" IS '采购凭证号';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."BUYER_CODE" IS '采购组织';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."BUYER_NAME" IS '采购组织描述';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."VENDOR_CODE" IS '供应商或债权人的帐号';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."VENDOR_NAME" IS '供应商名称 ';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."MATERIAL_CODE" IS '物料号 ';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."UNIT_NAME" IS '基本计量单位';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."REC_QTY" IS '入库数量';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."ITEM_NO" IS '行号';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."TYPE" IS '区分类别';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."FACTORY_CODE" IS '工厂编码';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."FACTORY_NAME" IS '工厂名称';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."ORDER_QTY" IS '退货数量';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."TXZ01" IS '短文本';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."BUYER_ID" IS '采购组织Id';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."VENDOR_ID" IS '供应商Id';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."GROUP_CODE" IS '采购组 ';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."GROUP_NAME" IS '采购组的描述';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."PRICE" IS '不含税单价';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."INVOICED_QUANTITY" IS '开票数量';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."CURRENCY_CODE" IS '货币码';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."DLV_CODE" IS 'ASN发货单号';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."MATERIAL_NAME" IS '物料名称';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."MATERIAL_ID" IS '物料Id';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."CHANGE_DATE" IS '更改日期';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."ORDER_NO" IS '采购凭证的项目编号';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."POST_DATE" IS '凭证中的过帐日期';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."MATERIAL_NO" IS '物料凭证编号';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."MATERIAL_PROJECT" IS '物料凭证中的项目';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."CON_INVOICED_QUANTITY" IS '仍要开票数量';
COMMENT ON COLUMN "QEWEB_VIEW_NO_CHECK_ITEM"."CON_PRICE" IS '仍要开票价格';

-- ----------------------------
-- Indexes structure for table QEWEB_VIEW_NO_CHECK_ITEM
-- ----------------------------

-- ----------------------------
-- Checks structure for table QEWEB_VIEW_NO_CHECK_ITEM
-- ----------------------------
ALTER TABLE "QEWEB_VIEW_NO_CHECK_ITEM" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table QEWEB_VIEW_NO_CHECK_ITEM
-- ----------------------------
ALTER TABLE "QEWEB_VIEW_NO_CHECK_ITEM" ADD PRIMARY KEY ("ID");
