--修改精度2位为3位

--1、QEWEB_PURCHASE_ORDER_ITEM表 
  --（1）PRICE
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (PRICE2  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set PRICE2=PRICE;

alter table QEWEB_PURCHASE_ORDER_ITEM drop (PRICE);


alter table QEWEB_PURCHASE_ORDER_ITEM rename column PRICE2 to PRICE;

 ---（2）DCOL1

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (DCOL1_1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set DCOL1_1=DCOL1;

alter table QEWEB_PURCHASE_ORDER_ITEM drop (DCOL1);


alter table QEWEB_PURCHASE_ORDER_ITEM rename column DCOL1_1 to DCOL1;

-----(3)DCOL2

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (DCOL2_2  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set DCOL2_2=DCOL2;

alter table QEWEB_PURCHASE_ORDER_ITEM drop (DCOL2);


alter table QEWEB_PURCHASE_ORDER_ITEM rename column DCOL2_2 to DCOL2;



-----(4)DCOL3

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (DCOL3_3  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set DCOL3_3=DCOL3;

alter table QEWEB_PURCHASE_ORDER_ITEM drop (DCOL3);


alter table QEWEB_PURCHASE_ORDER_ITEM rename column DCOL3_3 to DCOL3;


----(5)DCOL4
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (DCOL4_4  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set DCOL4_4=DCOL4;

alter table QEWEB_PURCHASE_ORDER_ITEM drop (DCOL4);


alter table QEWEB_PURCHASE_ORDER_ITEM rename column DCOL4_4 to DCOL4;

---(6)DCOL5
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (DCOL5_5  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set DCOL5_5=DCOL5;

alter table QEWEB_PURCHASE_ORDER_ITEM drop (DCOL5);


alter table QEWEB_PURCHASE_ORDER_ITEM rename column DCOL5_5 to DCOL5;

--(7)ONWAY_QTY
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (ONWAY_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set ONWAY_QTY1=ONWAY_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM drop (ONWAY_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM rename column ONWAY_QTY1 to ONWAY_QTY;

--(8)RECEIVE_QTY
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (RECEIVE_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set RECEIVE_QTY1=RECEIVE_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM drop (RECEIVE_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM rename column RECEIVE_QTY1 to RECEIVE_QTY;

--(9)UNDELIVERY_QTY
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (UNDELIVERY_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set UNDELIVERY_QTY1=UNDELIVERY_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM drop (UNDELIVERY_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM rename column UNDELIVERY_QTY1 to UNDELIVERY_QTY;
--(10)RETURN_QTY

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (RETURN_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set RETURN_QTY1=RETURN_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM drop (RETURN_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM rename column RETURN_QTY1 to RETURN_QTY;
--(11)DIFF_QTY

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM
 ADD (DIFF_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM set DIFF_QTY1=DIFF_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM drop (DIFF_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM rename column DIFF_QTY1 to DIFF_QTY;

-----2、-QEWEB_PURCHASE_ORDER_ITEM_PLAN-------
--RECEIVE_QTY
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (RECEIVE_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set RECEIVE_QTY1=RECEIVE_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (RECEIVE_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column RECEIVE_QTY1 to RECEIVE_QTY;

--RETURN_QTY
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (RETURN_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set RETURN_QTY1=RETURN_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (RETURN_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column RETURN_QTY1 to RETURN_QTY;

--TO_DELIVERY_QTY
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (TO_DELIVERY_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set TO_DELIVERY_QTY1=TO_DELIVERY_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (TO_DELIVERY_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column TO_DELIVERY_QTY1 to TO_DELIVERY_QTY;

--DELIVERY_QTY
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (DELIVERY_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set DELIVERY_QTY1=DELIVERY_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (DELIVERY_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column DELIVERY_QTY1 to DELIVERY_QTY;


--DIFF_QTY
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (DIFF_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set DIFF_QTY1=DIFF_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (DIFF_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column DIFF_QTY1 to DIFF_QTY;

---（2）DCOL1

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (DCOL1_1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set DCOL1_1=DCOL1;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (DCOL1);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column DCOL1_1 to DCOL1;

-----(3)DCOL2

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (DCOL2_2  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set DCOL2_2=DCOL2;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (DCOL2);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column DCOL2_2 to DCOL2;



-----(4)DCOL3

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (DCOL3_3  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set DCOL3_3=DCOL3;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (DCOL3);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column DCOL3_3 to DCOL3;


----(5)DCOL4
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (DCOL4_4  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set DCOL4_4=DCOL4;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (DCOL4);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column DCOL4_4 to DCOL4;

---(6)DCOL5
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (DCOL5_5  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set DCOL5_5=DCOL5;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (DCOL5);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column DCOL5_5 to DCOL5;
--ONWAY_QTY
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (ONWAY_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set ONWAY_QTY1=ONWAY_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (ONWAY_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column ONWAY_QTY1 to ONWAY_QTY;
--UNDELIVERY_QTY
ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (UNDELIVERY_QTY1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set UNDELIVERY_QTY1=UNDELIVERY_QTY;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (UNDELIVERY_QTY);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column UNDELIVERY_QTY1 to UNDELIVERY_QTY;


----3、QEWEB_DELIVERY----

ALTER TABLE QEWEB_PURCHASE_ORDER_ITEM_PLAN
 ADD (ANZPK1  NUMBER(11,3));

update QEWEB_PURCHASE_ORDER_ITEM_PLAN set ANZPK1=ANZPK;

alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN drop (ANZPK);


alter table QEWEB_PURCHASE_ORDER_ITEM_PLAN rename column ANZPK1 to ANZPK;



