ALTER TABLE QEWEB_ASSESS_INDEX ADD (LIMIT_POINTS NUMBER(11) DEFAULT 0);
COMMENT ON COLUMN QEWEB_ASSESS_INDEX.LIMIT_POINTS IS '扣分上限';

ALTER TABLE QEWEB_ASSESS_SCORES_TOTAL ADD (CORRECTION_STATUS NUMBER(1) DEFAULT 0);
COMMENT ON COLUMN QEWEB_ASSESS_SCORES_TOTAL.CORRECTION_STATUS IS '整改状态';
