CREATE TABLE QEWEB_FEEDBACK
(
  ID                 NUMBER(9)     primary key   NOT NULL,
  BILL_TYPE          NUMBER(9),
  BILL_ID            NUMBER(9),
  FEEDBACK_ORG_ID    NUMBER(11),
  FEEDBACK_ORG_NAME  NVARCHAR2(100),
  FEEDBACK_CONTENT   NVARCHAR2(250),
  RECV_ORG_ID        NVARCHAR2(100),
  CREATE_USER_ID     NUMBER(11),
  CREATE_USER_NAME   NVARCHAR2(255),
  CREATE_TIME        DATE,
  UPDATE_USER_ID     NUMBER(11),
  UPDATE_USER_NAME   NVARCHAR2(255),
  LAST_UPDATE_TIME   DATE,
  ABOLISHED          NUMBER(1)                  NOT NULL
);