ALTER TABLE QEWEB_STOREHOUSE ADD COL1 NVARCHAR2(100);
ALTER TABLE QEWEB_STOREHOUSE ADD COL2 NVARCHAR2(100);
ALTER TABLE QEWEB_STOREHOUSE ADD COL3 NVARCHAR2(100);
ALTER TABLE QEWEB_STOREHOUSE ADD COL4 NVARCHAR2(100);
ALTER TABLE QEWEB_STOREHOUSE ADD COL5 NVARCHAR2(100);
ALTER TABLE QEWEB_STOREHOUSE ADD COL6 NVARCHAR2(100);
ALTER TABLE QEWEB_STOREHOUSE ADD COL7 NVARCHAR2(50);


ALTER TABLE QEWEB_PRODUCT_LINE ADD COL1 NVARCHAR2(50);
ALTER TABLE QEWEB_PRODUCT_LINE ADD COL2 NVARCHAR2(50);
ALTER TABLE QEWEB_PRODUCT_LINE ADD COL3 NVARCHAR2(50);
ALTER TABLE QEWEB_PRODUCT_LINE ADD COL4 NVARCHAR2(50);
ALTER TABLE QEWEB_PRODUCT_LINE ADD COL5 NVARCHAR2(50);