/**
 * 操作日志
 */
CREATE TABLE QEWEB_OPERATION_JOURNAL
(
  ID                NUMBER        PRIMARY KEY   NOT NULL,
  ORG_NAME          NVARCHAR2(255),
  OPERATION_NAME    NVARCHAR2(255),
  CONTENT           NVARCHAR2(500),
  IP                NVARCHAR2(255),
  OS                NVARCHAR2(255),
  EXCEPTION         NVARCHAR2(255),
  ABOLISHED         NUMBER(1),
  CREATE_TIME       TIMESTAMP(6),
  CREATE_USER_ID    NUMBER(9),
  LAST_UPDATE_TIME  TIMESTAMP(6),
  UPDATE_USER_ID    NUMBER(9),
  CREATE_USER_NAME  NVARCHAR2(100),
  UPDATE_USER_NAME  NVARCHAR2(100),
  REQUEST_URL       NVARCHAR2(255),
  REQUEST_PAGE      NVARCHAR2(255),
  USER_LOGIN        NVARCHAR2(255)
);