DROP TABLE QEWEB_BUS_OPERATE_LOG CASCADE CONSTRAINTS;

CREATE TABLE QEWEB_BUS_OPERATE_LOG
(
  ID                NUMBER(11)   PRIMARY KEY    NOT NULL,
  RECORD            NUMBER(11)                  NOT NULL,
  CLASSZ            NVARCHAR2(128)              NOT NULL,
  OPERATE           NVARCHAR2(128)              NOT NULL,
  OBJ_CLASSZ        NVARCHAR2(128)              NOT NULL,
  CONTENT           NVARCHAR2(2000),
  ABOLISHED         NUMBER(1)                   NOT NULL,
  CREATE_TIME       TIMESTAMP(6),
  CREATE_USER_ID    NUMBER(9),
  LAST_UPDATE_TIME  TIMESTAMP(6),
  UPDATE_USER_ID    NUMBER(9),
  CREATE_USER_NAME  NVARCHAR2(100),
  UPDATE_USER_NAME  NVARCHAR2(100)
);

COMMENT ON TABLE QEWEB_BUS_OPERATE_LOG IS '业务操作单据记录';
COMMENT ON COLUMN QEWEB_BUS_OPERATE_LOG.ID IS '主键ID';
COMMENT ON COLUMN QEWEB_BUS_OPERATE_LOG.RECORD IS '记录ID';
COMMENT ON COLUMN QEWEB_BUS_OPERATE_LOG.CLASSZ IS '操作业务类';
COMMENT ON COLUMN QEWEB_BUS_OPERATE_LOG.OPERATE IS '操作方法';
COMMENT ON COLUMN QEWEB_BUS_OPERATE_LOG.OBJ_CLASSZ IS '操作对象';
COMMENT ON COLUMN QEWEB_BUS_OPERATE_LOG.CONTENT IS '数据内容';