ALTER TABLE QEWEB_VENDOR_MATERIAL_REL ADD COL1 NVARCHAR2(50);
ALTER TABLE QEWEB_VENDOR_MATERIAL_REL ADD COL2 NVARCHAR2(50);
ALTER TABLE QEWEB_VENDOR_MATERIAL_REL ADD COL3 NVARCHAR2(50);
ALTER TABLE QEWEB_VENDOR_MATERIAL_REL ADD COL4 NVARCHAR2(50);
ALTER TABLE QEWEB_VENDOR_MATERIAL_REL ADD COL5 NVARCHAR2(50);
ALTER TABLE QEWEB_VENDOR_MATERIAL_REL ADD COL6 NVARCHAR2(50);
ALTER TABLE QEWEB_VENDOR_MATERIAL_REL ADD COL7 NVARCHAR2(50);
ALTER TABLE QEWEB_VENDOR_MATERIAL_REL ADD COL8 NVARCHAR2(50);